### ISSUE TITLE
Version 1.3 deletes previews replys / comments!

### ISSUE THREAD

**Issue by staion16** [physcocode/the-wire-pro#3]
Thank you for thi update, but it seems after I update to the current latest update 1.3, all my previews replys on wire posts have disapeared. Is this permanent?

**Comment by physcocode** [comment]
it does not delete the previous replies and comments its just hidden , because the comment entities are not different the old replies are not shown as comment , but if I unhide them then they will be shown as normal wire post with type "reply" 

also its not permanent disabling wire pro will unhide all old replies , this DOES NOT DELETE the old replies :)
